---
title: "MRL Implementation - Gold Standard"
output: html_notebook
---

```{r}
#Packages and Settings
## Run once: devtools::install_github("sarahlotspeich/imputeCensRd")
library(imputeCensRd)
library(tidyverse)
set.seed(317) #brought to you live from my St. Patrick's Day adventures!
censoring = "light" # censoring rate
n = 1000 
```

```{r}
#write survival function where q is an instance of X
trueSURV <- function(q, z) {
  pweibull(q = q, shape = 0.75, scale = 0.25, lower.tail = FALSE)
}
```

```{r}
#The Data Generation Block
z <- rbinom(n = n, size = 1, prob = 0.5) # Uncensored covariate
x <- rweibull(n = n, shape = 0.75, scale = 0.25) # To-be-censored covariate
q <- ifelse(censoring == "light", 2, 
           ifelse(censoring == "moderate", 0.35, 0.05)) # Rate parameter for censoring
c <- rweibull(n = n, shape = 1, scale = q) # Random censoring mechanism
w <- pmin(x, c) # Observed covariate value
d <- as.numeric(x <= c) # "Event" indicator
surv <- trueSURV(x,z)

integral_uses_x <- rep(NA, times = n)
for(i in 1:n) {
  integral_uses_x[i] <- integrate(trueSURV, lower = x[i], upper = Inf)$value
}

mrl_uses_x <- integral_uses_x / surv

integral_uses_w <- rep(NA, times = n)
for(i in 1:n) {
  integral_uses_w[i] <- integrate(trueSURV, lower = w[i], upper = Inf)$value
}
mrl_uses_w <- integral_uses_w/surv

dat <- data.frame(x,w,z,d = as.factor(d),mrl_uses_x, mrl_uses_w) # Construct dataset
```

```{r}
#how's it looking?
dat |>
  ggplot(aes(x = x, y = mrl_uses_w)) +
  geom_point(aes(x = w, y = mrl_uses_x, shape = d), color = "blue", alpha = 0.5) +
  geom_point(aes(x = w, y = mrl_uses_w, shape = d), color = "magenta", alpha = 0.5) +
  labs(x = "W",
       y = "MRL",
       title = "Gold Standard?",
       subtitle = "Blue for MRL(X), Pink for MRL(W)") +
  theme_bw()
```



